version: "3.9"  
services:
 db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass
    volumes:
      - mysql-data:/var/lib/mysql
      - dataset-proj/smsCorpus_en_2015.03.09_all.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: {}
