version: "3.8"  
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dataset-proj/smsCorpus_en_2015.03.09_all.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - 3306:3306
 
  superset:
    build:
      context: ./superset
    ports:
      - 8080:8088
 
volumes:
  mysql-data: {}
